#奖励设置
Reward-Settings:
    #权限组优先级，顺序从上到下
    Groups-Priority:
    - VIP
    - Default
    #权限组设置
    Permission-Groups:
        #这个是默认组，不可删除也无法添加权限
        Default:
            #正常签到时触发
            Normal-Time:
                #在签到时发送信息
                #支持PlaceholderAPI变量
                Messages: 
                - '{prefix}&a签到奖励已获取.'
                #在签到时奖励物品
                #在这个选项中，你可以直接填写原版物品的名字，
                #或者是RewardSettings.yml中（包含手动设置的、用命令添加的）的物品。
                #格式： "[物品名字|收藏品名字]:[数量]"
                #示例： "diamond:5" 奖励5个钻石
                #你可以使用 "[最小值]-[最大值]" 以随机奖励物品的数量。
                #示例： "diamond:1-3" 随机奖励1-3个钻石。
                Reward-Items:
                - 'diamond:1'
                - 'gold_ingot:3'
                - 'iron_ingot:6'
                #在签到时发送广播信息
                #在此选项中的信息将会被所有人看见
                Broadcast-Messages: []
                #在签到时播放声音
                #格式： [声音]-[音量]-[音调]-[是否所有人都能听见]
                Play-Sounds: 
                - 'ORB_PICKUP-1-1-FALSE'
                #在签到时执行命令
                #格式： "[执行类型]:[命令]"
                #"执行类型" 可以是 "op" 、 "server"、 无
                #分别对应 "玩家以OP权限执行命令"、 "执行控制台命令"、"玩家执行命令"
                #示例： 
                # "server:say hello" 在控制台中执行"say hello"命令
                # "op:gamemode creative" 玩家以OP权限执行"gamemode creative"命令
                # "spawn" 玩家正常执行"spawn"命令
                #支持PlaceholderAPI变量
                Commands: []
            #当玩家使用补签卡进行补签时触发
            Retroactive-Time:
                #禁止玩家通过补签获得以下模块的奖励
                Disabled-Modules:
                    #建议开启， 以防止玩家直接获得某些特殊日期的专属奖励
                    Special-Dates: true
                    Special-Week-Days: true
                    Statistics-Times: false
                    Statistics-Times-Of-Month: false
                    Statistics-Times-Cycle: false
                    Custom-Date-And-Time-Periods: false
                Reward-Items:
                - 'diamond:1'
                - 'gold_ingot:3'
                - 'iron_ingot:6'
                Play-Sounds: 
                - 'ORB_PICKUP-1-1-FALSE'
            #连续签到一定次数时触发
            Special-Times:
                #三次
                3:
                    #是否覆盖正常签到下的奖励
                    Override-default-rewards: true
                    Messages: 
                    - '{prefix}&a连续签到三天！ 奖励&e翻倍&a！'
                    Broadcast-Messages:
                    - '{prefix}&a玩家 &e{player} &a连续签到了三天!'
                    Play-Sounds: 
                    - 'LEVELUP-1-0-TRUE'
                    Reward-Items:
                    - 'diamond:1'
                    - 'gold_ingot:3'
                    - 'iron_ingot:6'
                #七次
                7:
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&a连续签到一周！额外赠送附魔&e&l钻石剑&a与&e&l金苹果&a！'
                    Broadcast-Messages:
                    - '{prefix}&a玩家 &e{player} &a连续签到了一周!'
                    Play-Sounds: 
                    - 'LEVELUP-1-0-TRUE'
                    Reward-Items:
                    - 'Super_Diamond_Sword:1'
                    - 'golden_apple:1'
            #周期性连续签到一定次数时触发
            Special-Times-Cycle:
                #每连续签到三天的奖励
                3:
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&a你周期性连续签到了三天，额外奖励一个金苹果！'
                    Reward-Items:
                    - 'golden_apple:1'
            #特别星期签到时触发
            Special-Week-Days:
                #周日
                7:
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&a今天是周末，额外奖励一个金苹果！'
                    Reward-Items:
                    - 'golden_apple:1'
            #签到累计达到一定次数时触发
            Statistics-Times:
                100:
                    Messages: 
                    - '{prefix}&a签到次数总计达到100次，获得&e10000&a游戏硬币。'
                    Commands:
                    - 'server:eco give {player} 10000'
            #周期性签到累计达到一定次数时触发
            Statistics-Times-Cycle:
                #总计签到次数每100次的奖励
                100:
                    Messages: 
                    - '{prefix}&a签到次数100次，获得&e5000&a游戏硬币。'
                    Commands:
                    - 'server:eco give {player} 5000'
            #在自定义日期时间段的进行签到时触发
            Custom-Date-And-Time-Periods:
                #格式：
                #    "年-月-日" 代表具体日期
                #    "时-分-秒" 代表具体时间
                #    "年-月-日 时:分:秒" 代表具体日期时间
                #    "年-月-日 时:分:秒 ~ 年-月-日 时:分:秒" 代表具体日期时间段（从开始到结束）
                #示例: 
                #    '2015-8-11' 即2015年8月11日全天签到有效 
                #    '8:00:00' 即每一天的8:00:00签到有效
                #    '2015-8-11~2025-8-11' 即2015年8月11日到2025年8月11日签到有效
                #    '8:00:00~12:00:00' 即每一天的8:00:00到12:00:00签到有效
                #混合使用:
                #    '2015-8-11 12:00:00' 即2015年8月11日的12时0分0秒签到有效
                #    '2015-8-11 12:00:00~2025-8-11 12:00:00' 即2015年8月11日的12时0分0秒到2025年8月11日的12时0分0秒时签到有效
                #注意: 
                #日期和时间必须至少有其中一个，它们之间之间需要有空格。
                #日期可以只填写"月份-日期"或"日期"，代表每年、每月都有效。
                #使用"~"符号代表连接两个时间段。
                #以下条件可以共存，即如果同时满足多个日期时间段，则可以获取多个奖励。
                '2015-8-11~2025-8-11': #从2015年8月11日零时到2025年8月11日零时
                    Override-default-rewards: false
                    Reward-Items:
                    - 'diamond:1'
                '12:00:00~15:00:00': #每日12时0分0秒到15时0分0秒
                    Override-default-rewards: false
                    Reward-Items:
                    - 'diamond:1'
                '2015-8-11 12:00:00~2025-8-11 15:00:00': #2015年8月11日12时0分0秒到2025年8月11日15时0分0秒
                    Override-default-rewards: false
                    Reward-Items:
                    - 'diamond:1'
                '12-25 19:00:00 ~ 23:59:59': #圣诞节当天19点0分0秒到23点59分59秒
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&a现在是圣诞夜，祝您圣诞快乐。'
                    Reward-Items:
                    - 'apple:64'
            #在特殊日期进行签到时触发
            #注：当前配置项已过时，推荐更高级的配置项 "Custom-Date-And-Time-Periods"
            Special-Dates:
                #格式: MM-dd （月-日）注意不要把如一月一号写成“1-1”，而是“01-01”
                '12-25':
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&a今天是圣诞节， 圣诞节快乐！'
                    Reward-Items:
                    - 'apple:64'
            #在特殊时间段进行签到时触发
            #注：当前配置项已过时，推荐更高级的配置项 "Custom-Date-And-Time-Periods"
            Special-Time-periods:
                #格式： 时:分:秒， 从左往右
                #最小值: 00:00:00 ,最大值: 23:59:59
                #不填写分或秒泛指此分钟或秒钟可以是任意时间段
                #如: '12:00' 指 '12:00:00-12:00:59'
                #    '12' 指 '12:00:00-12:59:59'
                #晚上十点半
                '22:30:00':
                    #检测方案，分别为： ON_TIME, AFTER_THIS_TIME, BEFORE_THIS_TIME
                    #分别对应： 准时签到， 在这之后签到， 在这之前签到
                    Option: AFTER_THIS_TIME #在22:30:00之后签到
                    #时间限制，如果您的方案是准时签到以外的方案，你可以在这里设置上限时间
                    #“23:59:59” 在这里表示将会在每一天的22:30:00到23:59:59签到时触发
                    Time-Limit: '23:59:59'
                    Override-default-rewards: true
                    Messages: 
                    - '{prefix}&a夜已深， 注意休息！'
                    #深夜一杯牛奶助眠（误）
                    Reward-Items:
                    - 'milk_bucket:1'
                #凌晨三点
                '03:00:00':
                    Option: BEFORE_THIS_TIME #在03:00:00之前签到
                    #03:00:00前到00:00:00时签到时触发
                    Time-Limit: '00:00:00'
                    Override-default-rewards: true
                    Messages: 
                    - '{prefix}&a夜已深， 注意休息！'
                    Reward-Items:
                    - 'milk_bucket:1'
            #每日签到时得到指定名次时触发
            Special-Ranking:
                #全服第一名
                '1':
                    Override-default-rewards: true
                    Messages: 
                    - '{prefix}&a你今天是全服第一个签到的玩家，奖励翻倍！'
                    Reward-Items:
                    - 'diamond:1'
                    - 'gold_ingot:3'
                    - 'iron_ingot:6'
            #每月连续签到一定次数时触发
            Special-Times-Of-Month:
                #十五次
                15:
                    #生效的月份，请填入月份对应的数字
                    Valid-Months: [1, 2, 3] #即为每年一月、二月、三月生效
                    #是否覆盖正常签到下的奖励
                    Override-default-rewards: true
                    Messages: 
                    - '{prefix}&a本月连续签到达到了15天，签到奖励&e翻倍&a！'
                    Reward-Items:
                    - 'diamond:1'
                    - 'gold_ingot:3'
                    - 'iron_ingot:6'
            #每月签到累计达到一定次数时触发
            Statistics-Times-Of-Month:
                #十五次
                15:
                    #生效的月份，请填入月份对应的数字
                    Valid-Months: [1, 2, 3] #即为每年一月、二月、三月生效
                    #是否覆盖正常签到下的奖励
                    Override-default-rewards: true
                    Messages: 
                    - '{prefix}&a本月签到次数总计达到15次，获得&e1000&a游戏硬币。'
                    Commands:
                    - 'server:eco give {player} 1000'
        #这个是自定义的组，以示范
        VIP:
            #使用权限
            #当玩家拥有这个权限时，将会采用这个组的参数
            #前提是你没有搞错组与组之间的优先级！
            Permission: signin.reward.vip
            Normal-Time:
                Messages: 
                - '{prefix}&a签到奖励已获取.'
                Reward-Items:
                - 'diamond:3'
                - 'gold_ingot:9'
                - 'iron_ingot:12'
                Commands: 
                - 'server:points give {player} 10'
            Retroactive-Time:
                Disabled-Modules:
                    Special-Dates: true
                    Special-Times: true
                Reward-Items:
                - 'diamond:2'
                - 'gold_ingot:6'
                - 'iron_ingot:12'
            Special-Times:
                3:
                    Override-default-rewards: true
                    Messages: 
                    - '{prefix}&a连续签到三天！ 奖励&e翻倍&a！'
                    Reward-Items:
                    - 'diamond:6'
                    - 'gold_ingot:18'
                    - 'iron_ingot:24'
                    Commands: 
                    - 'server:points give {player} 20'
                7:
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&a连续签到一周！额外赠送附魔&e&l钻石剑&a与&e&l金苹果&a！'
                    Reward-Items:
                    - 'Super_Diamond_Sword:1'
                    - 'golden_apple:1'
            Statistics-Times:
                100:
                    Messages: 
                    - '{prefix}&a签到次数总计达到100次，获得&e10000&a游戏硬币。'
                    Commands:
                    - 'server:eco give {player} 10000'
            Special-Dates:
                '12-25':
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&a今天是圣诞节， 圣诞节快乐！'
                    Reward-Items:
                    - 'apple:64'